# Loss function
The derivative of loss function with respect to weight is used to update the weight using the formula: New Weight = Old Weight − (Learning Rate × Derivative)

Different types of loss functions:

cost function = sum(yi - yi')

loss function or mean error = (1/n)(sum(yi - yi'))

mean square error = (1/n)(sum(yi - yi')^2)

log loss or binary cross entropy = -(1/n)( sum(yi(log(yi')) - (1 - yi)(log(1 - yi)) )

In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [3]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [4]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


np.float64(0.5)

In [5]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.5)

In [7]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [8]:
mae_np(y_predicted, y_true)

np.float64(0.5)

In [9]:
np.log([0])

C:\Users\Diya Dholakia\AppData\Local\Temp\ipykernel_14952\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [10]:
epsilon = 1e-15

In [11]:
np.log([1e-15])

array([-34.53877639])

In [12]:
y_predicted

array([1, 1, 0, 0, 1])

In [13]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [14]:
1-epsilon

0.999999999999999

In [15]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [16]:
y_predicted_new = np.array(y_predicted_new)

In [17]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [18]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(17.2696280766844)

In [19]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [20]:
log_loss(y_true, y_predicted)

np.float64(17.2696280766844)

we convert 1 to 1- and 0 to 0+ because we don't want -inf and 0 as values of log